[tool.poetry]
name = "mlsp"
version = "0.1.0"
description = ""
authors = ["s"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.8.10"
streamlit = "^1.32.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
